### PR TITLE
golang/dep init

### PR DESCRIPTION
**Pull request by aaronsheah**
* use [dep](https://github.com/golang/dep) to manage dependencies
* ran `dep init`

### CODE REVIEW

**Comment by aaronsheah** [comment]
requesting review: @yauhen-l

**Comment by yauhen-l** [comment]
Hi @aaronsheah,
Sorry for delay, will check it soon.

**Comment by yauhen-l** [comment]
@aaronsheah could you please add few words to `README.md`?
I mean add note that project uses `dep` and link to it.

**Comment by aaronsheah** [comment]
Sorry for taking so long to do this (simple change)

**Comment by yauhen-l** [comment]
@aaronsheah thank you. I am fine with changes and going to merge them.
Also I think about adding `dep ensure` to Travis CI script and check that there is no diff.
What do you think?

**Comment by aaronsheah** [comment]
@yauhen-l we can do `dep ensure` and check diff as a start. Looks like there might be `dep check` coming in the future. [dep check](https://docs.google.com/document/d/1j_Hka8eFKqWwGJWFSFedtBsNkFaRN3yvL4g8k30PLmg/edit)

**Pull request merged**
